# -*- coding: utf-8 -*-
"""06.02.2024.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IpxblZq7yvD-B_YOAg8RR63-pVtr7Usx

OPERADORES
"""

X= 6 + 4 * 2

print('X=', X)

A= (4*9+5)

print('A=', A)

B= ((6+7)* 9)

print('B=', B)

C= (15+20-30)

print('C=', C)

D= (6+5**2)

print('D=', D)

"""ATRIBUIÇÃO"""

X=8
print(X)
X+=5
print(X)
X=8
X-=4
print(X)
X=8
X*=20
print(X)
X=8
X/=2
print(X)

"""COMPARADORES"""

X=8
X1=3

X_Result = X < X1
X_Resul = X == X1
X_Resu = X >= X1
X_Res = X != X1

print (X_Result)
print (X_Resul)
print (X_Resu)
print (X_Res)

"""LOGICOS"""

X=4
X1=5

print(X != 5 or X > X1)

"""IDENTIDADE"""

time_carlos = 'Botafogo'
time_luciano = 'Flamengo'
time_fabricia = 'Botafogo'

print( time_carlos is not time_luciano)
print( time_carlos is time_fabricia)

x1 = "botafogo"
x2 = "flamengo"
x3 = "botafogo"

Xresult = x1 is x3
print(Xresult)
Xresult = x1 is not x3
print(Xresult)
Xresult = x1 is x2
print(Xresult)
Xresult = x2 is not x3
print(Xresult)

"""ASSOCIAÇÃO"""

frutas = ["banana","laranja","uva","ameixa"]

x1 = "banana"
x2 ="laranja"
x3 = "abacaxi"

Xresult = x1 in frutas
Xresul = x1 not in frutas
Xresu = x2 not in frutas
Xres = x3 in frutas

print (Xresult, Xresul, Xresu, Xres)