# -*- coding: utf-8 -*-
"""07.02.2024.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZHlSdzlqDeDCTrKFv2uE9dmfS6qQwPc5
"""

X =4
X1 = 9
X2 = 5

Xresult = (((2 + 5) * 3) + X + 5) < X1
Xresul = (((2 + 5) * 3) + (X + 5 + X1) == (X == 6 + X2 * 2))
Xresu = (((3 * 6) + X -3) < X2)
Xres = (((7 * 8) > (X + 4 + X1) < (X ** 2 + X2 * 9)))

print (Xresult, Xresul, Xresu, Xres)

"""UTILIZE OPERADORES LÓGICOS PARA VERIFICAR SE UM NÚMERO N ESTÁ ENTRE 20 E 30"""

N= 20

print (N > 20 and N < 30)

"""ESCREVA UMA EXPRESSÃO LÓGICA QUE SEJA TRUE APENAS SE A FOR MAIOR DO QUE 10 E B FOR MENOR OU IGUAL A 5"""

A = 11
B = 5

print (A > 10 and B <= 5)

"""ESCREVA UMA EXPRESSÃO LÓGICA QUE SEJA FALSE APENAS SE A FOR MAIOR OU IGUAL A 10 OU B FOR MENOR DO QUE 5"""

A = 10
B = 4

print ( A <= 9 or B >= 5)