# -*- coding: utf-8 -*-
"""07.02.2024-02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jc1V0tM-2DzcLRC9EHizB8XHeaRH9E2m

LER DUAS NOTAS DE UM ALUNO, EFETUAR A MÉDIA ARITMÉTICA E, CASO A MÉDIA SEJA MAIOR OU IGUAL A 7, INFORMAR QUE O ALUNO FOI APROVADO.
"""

NOTA1 = 8
NOTA2 = 8

MEDIA = (NOTA1 + NOTA2) / 2

if (MEDIA >= 7):
  print("Aluno aprovado com média: ", MEDIA)
else:
  print ("Aluno reprovado com média: ", MEDIA)

"""```
NOTA1, NOTA2, MEDIA: real
ESCREVA ("INSIRA A NOTA 1 E A NOTA 2: ")
LEIA (NOTA1, NOTA2)
MEDIA = (NOTA1 + NOTA2) / 2
SE (MEDIA >= 7){
  ESCREVA ("ALUNO APROVADO COM NOTA: ", MEDIA)
}
SENAO{
  ESCREVA ("ALUNO REPROVADO COM NOTA: ", MEDIA)
}

```



"""