# -*- coding: utf-8 -*-
"""08.02.2024.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_X5HxfWj0BiwPXcXQDp_dyuE_XwmK0cg

1. Leia dois números, faça a soma e apresente caso seja maior que 15.
"""

n1 = int(input())
n2 = int(input())

if (n1 + n2 > 15):
  print("A soma é: ", n1 + n2)
else:
  print("Valor restrito.")

"""2. Faça um programa que recebendo um valor inteiro, informe se o número é positivo,
negativo ou neutro.

"""

numero = int(input())
if(numero > 0):
  print("O valor é positivo.")
elif(numero < 0):
  print("O valor é negativo")
else:
  print("O valor é neutro")

"""3. Leia a idade e informe se a pessoa é maior ou menor de idade"""

idade = int(input("Digite sua idade: "))
if (idade >= 18):
  print("Maior de idade.")
else:
  print("Menor de idade.")

"""4. Faça um programa que pergunte a temperatura atual para o usuário e mostre uma
mensagem na tela dizendo se está “quente”, “frio” ou “agradável”.

"""

temperatura = float(input("Nos informe a temperatura: "))

if(temperatura <= 22):
  print("Está frio!")
elif(temperatura > 22 and temperatura <= 28):
  print("Está agradável!")
else:
  print("Está quente!")

"""5. Faça um programa em linguagem Python que leia dois números inteiros e informe
se estes são iguais ou diferentes.
"""

n1 = int(input("Insira numero 1: "))
n2 = int(input("Insira numero 2:"))

if(n1 is n2):
  print("Números iguais.")
else:
  print("Números diferentes.")

"""6. Escreva um programa que verifique a validade de uma senha fornecida pelo
usuário. A senha válida é o número 1234. Devem ser impressas as seguintes
mensagens:
"""

password = int(input("Insira sua senha: "))

if(password != 1234):
  print("ACESSO NEGADO.")
else:
  print("ACESSO PERMITIDO.")

"""7. Ler duas notas de um aluno, efetuar a média aritmética e, se a média for maior ou
igual a 7, informar que o aluno foi aprovado; se a média for maior ou igual a 5 mas
menor do que 7, informar que o aluno está de exame; se a média for menor do que
5 informar que o aluno foi reprovado.
"""

n1 = float(input("Insira nota 1: "))
n2 = float(input("Insira nota 2: "))

media = (n1 + n2) / 2
if(media >= 7):
  print("Aluno aprovado.")
elif(media >= 5 and media < 7):
  print("Aluno necessita de exame.")
else:
  print("Aluno reprovado.")

"""8. Desenvolva um programa que recebe do usuário o placar de um jogo de futebol (os
gols de cada time) e informe se o resultado foi um empate, se a vitória foi do
primeiro time ou do segundo time.
"""

time1 = int(input("Insira o placar do time 1: "))
time2 = int(input("Insira o placar do time 2: "))

if (time1 > time2):
  print("Time 1 venceu!")
elif(time2 > time1):
  print("Time 2 venceu!")
else:
  print("Os times empataram!")

"""9. Faça um Programa que pergunte em que turno você estuda. Peça para digitar Mmatutino ou V-Vespertino ou N- Noturno. Imprima a mensagem "Bom Dia!", "Boa
Tarde!" ou "Boa Noite!" ou "Valor Inválido!", conforme o caso.
"""

print("Digite qual turno você estuda: ")
print("[M] Manhã")
print("[V] Vespertino")
print("[N] Noturno")

turno = str(input())
if(turno == "M"):
  print("Bom dia!")
elif(turno == "V"):
  print("Boa tarde!")
elif(turno == "N"):
  print("Boa noite!")
else:
  print("Valor Inválido.")

"""10. Faça um programa que solicite ao usuário sua idade, depois disso, exiba a
classificação etária de acordo com as faixas de valores:
 Criança para 0 até 11 anos;
 Adolescente para 12 até 18 anos;
 Jovem para 19 até 24 anos;
 Adulto para 25 até 40 anos;
 Meia Idade para 41 até 60 anos;
 Idoso acima de 60 anos.
"""

idade = int(input("Insira sua idade:"))
if(idade > 0 and idade <= 11):
  print("Criança.")
elif(idade >= 12 and idade <= 18):
  print("Adolescente.")
elif(idade >= 19 and idade <= 24):
  print("Jovem.")
elif(idade >= 25 and idade <= 40):
  print("Adulto.")
elif(idade >= 41 and idade <= 60):
  print("Meia idade.")
else:
  print("Idoso.")

"""11. As Organizações Tabajara resolveram dar um aumento de salário aos seus
colaboradores e lhe contrataram para desenvolver o programa que calculará os
reajustes. Faça um programa que recebe o salário de um colaborador e o reajuste
segundo o seguinte critério, baseado no salário atual:
 salários até R$ 280,00 (incluindo) : aumento de 20%
 salários entre R$ 280,00 e R$ 700,00 : aumento de 15%
 salários entre R$ 700,00 e R$ 1500,00 : aumento de 10%
 salários de R$ 1500,00 em diante : aumento de 5%
Após o aumento ser realizado, informe na tela:
 o salário antes do reajuste;
 o percentual de aumento aplicado;
 o valor do aumento;
 o novo salário, após o aumento.
"""

salario_anterior = float(input("Informe seu salário atual:"))
if(salario_anterior <= 280):
  aumento = salario_anterior * 0.2
  salario = salario_anterior + aumento

  print(f"Seu salario anterior era {salario_anterior}, foi aplicado aumento de 20%, somando {aumento} sendo seu salario atual: {salario}")
elif(salario_anterior > 280 and salario_anterior <= 700):
  aumento = salario_anterior * 0.15
  salario = salario_anterior + aumento

  print(f"Seu salario anterior era {salario_anterior}, foi aplicado aumento de 15%, somando {aumento} sendo seu salario atual: {salario}")
elif(salario_anterior > 700 and salario_anterior <= 1500):
  aumento = salario_anterior * 0.1
  salario = salario_anterior + aumento

  print(f"Seu salario anterior era {salario_anterior}, foi aplicado aumento de 10%, somando {aumento} sendo seu salario atual: {salario}")
elif(salario_anterior > 1500):
  aumento = salario_anterior * 0.05
  salario = salario_anterior + aumento

  print(f"Seu salario anterior era {salario_anterior}, foi aplicado aumento de 5%, somando {aumento} sendo seu salario atual: {salario}")

"""12. Faça um Programa que leia um número e exiba o dia correspondente da semana.
(1-Domingo, 2- Segunda, etc.), se digitar outro valor deve aparecer valor inválido.
"""

dia = int(input("Insira o dia de 1 a 7: "))

if(dia == 1):
  print("O dia é domingo.")
elif(dia == 2):
  print("O dia é segunda-feira")
elif(dia == 3):
  print("O dia é terça-feira.")
elif(dia == 4):
  print("O dia é quarta-feira")
elif(dia == 5):
  print("O dia é quinta-feira")
elif(dia == 6):
  print("O dia é sexta-feira")
elif(dia == 7):
  print("O dia é sábado")
else:
  print("Valor inválido.")

"""13. Faça um programa que pergunte ao usuário se ele quer passar uma temperatura de
Fahrenheit para Celsius ou de Celsius para Fahrenheit, e que, a partir da resposta
do usuário, faça a devida conversão.
"""

from inspect import TPFLAGS_IS_ABSTRACT
print("Deseja converter a temperatura em qual fluxo :")
print("[1] Fahrenheit para Celsius")
print("[2] Celsius para Fahrenheit")

fluxo = int (input())

if(fluxo == 1):
  t_f = float(input("Informe a temperatura em Fahrenheit: "))
  t_c = (t_f - 32) / 1.8

  print(f"A temperatura {t_f} em Celsius é igual a: {t_c}")
elif(fluxo == 2):
  t_c = float(input("Informe a temperatura em Celsius: "))
  t_f = (t_c * 1.8) + 32

  print(f"A temperatura {t_c} em Celsius é igual a: {t_f}")
else:
  print("Valor inválido.")

"""14. Faça um programa que receba a idade de uma pessoa e imprima sua condição
(obrigatória, optativa ou proibida), em relação ao ato de votar, conforme
apresentado abaixo:
 Pessoas com idade menor que 16 anos são proibidas de votar (proibido);
 Pessoas com idade igual a 16 e menor que 18 anos não são obrigadas a votar
(optativo);
 Pessoas com idade igual a 18 e menor que 65 anos são obrigadas a votar
(obrigatório);
 Pessoas com idade igual ou maior a 65 anos não são obrigadas a votar (optativo).

"""

idade = int(input("Informe a idade: "))

if(idade < 16):
  print("Proibido de votar.")
elif(idade >= 16 and idade < 18):
  print("Voto opcional.")
elif(idade >= 18 and idade < 65):
  print("Voto obrigatório.")
else:
  print("Voto opcional.")

"""15. Faça um programa que faça 5 perguntas para uma pessoa sobre um crime. As
perguntas são:
 “Telefonou para a vítima? “
 “Esteve no local do crime?”
 “Mora perto da vítima? “
 “Devia para a vítima? “
 “Já trabalhou com a vítima? “
"""

print("Interrogatório:")
p1 = str(input("Telefonou para a vítima: "))
p2 = str(input("Esteve no local do crime: "))
p3 = str(input("Mora perto da vítima: "))
p4 = str(input("Devia para a vítima: "))
p5 = str(input("Já trabalhou com a vítima: "))

print(p1)
print(p2)
print(p3)
print(p4)
print(p5)

"""16. O programa deve no final emitir uma classificação sobre a participação da pessoa
no crime. Se a pessoa responder positivamente a 2 questões ela deve ser
classificada como “Suspeita”, entre 3 e 4 como “Cúmplice” e 5 como “Assassino“.
Caso contrário, ele será classificado como “Inocente“.

"""

cont = int()
print("Interrogatório (SIM OU NÃO):")
p1 = str(input("Telefonou para a vítima: "))
p2 = str(input("Esteve no local do crime: "))
p3 = str(input("Mora perto da vítima: "))
p4 = str(input("Devia para a vítima: "))
p5 = str(input("Já trabalhou com a vítima: "))

if (p1 == "sim"):
  cont += 1
if (p2 == "sim"):
  cont += 1
if (p3 == "sim"):
  cont += 1
if (p4 == "sim"):
  cont += 1
if (p5 == "sim"):
  cont += 1

if(cont == 2):
  print("Suspeito.")
elif(cont > 2 and cont < 5):
  print("Cúmplice.")
elif(cont == 5):
  print("Assassino.")
else:
  print("Inocente.")

"""17. Faça um programa que pergunte o preço de três produtos e informe qual produto
você deve comprar, sabendo que a decisão é sempre pelo mais barato.
"""

print("Insira o valor dos três produtos: ")
pr1 = float(input("Produto 1: "))
pr2 = float(input("Produto 2: "))
pr3 = float(input("Produto 3: "))

if (pr1 < pr2 and pr1 < pr3):
  print("Compre o produto 1.")
elif(pr2 < pr1 and pr2 < pr3):
  print("Compre o produto 2.")
else:
  print("Compre o produto 3.")